        !COMPILER-GENERATED INTERFACE MODULE: Thu May 09 12:00:40 2019
        MODULE CONVERT_PK1_TO_COCHI__genmod
          INTERFACE 
            SUBROUTINE CONVERT_PK1_TO_COCHI(F,COCHI,PK1,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: F(2,2,N)
              REAL(KIND=8) :: COCHI(2,2,N)
              REAL(KIND=8) :: PK1(2,2,N)
            END SUBROUTINE CONVERT_PK1_TO_COCHI
          END INTERFACE 
        END MODULE CONVERT_PK1_TO_COCHI__genmod
